<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
		<div class="footer_container">
			<div class="footer_page container">		
				<div class="column1 fleft">
					<ul class="unstyled">
						<li>item</li>
						<li>item</li>
						<li>item</li>
						<li>item</li>
						<li>item</li>
					</ul>
				</div>
			</div>
		</div>
    </body>
</html>
